name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up SSH key
        uses: |
           echo "$EC2_KEY" | sed 's/\\n/\n/g' > private_key.pem
           chmod 600 private_key.pem
           ls -l private_key.pem  # Debug: Check if file exists
           head -n 5 private_key.pem  # Debug: Print first 5 lines

       
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/node-js-sample
            git pull origin main
            docker build -t my-node-app .
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d -p 80:5000 my-node-app

               docker build -t my-node-app
               docker stop my-node-app || true
               docker rm  my-node-app || true
               docker run -d -p 80:5000 my-node-app 
